name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          CI='' npm run build
      - name: Firebase Deploy
        run: |
          sudo npm install -g firebase-tools --unsafe-perm
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
